-- Migration Script: Create booking_requests table and setup sequence + reference trigger

-- 1. Create sequence for booking references
CREATE SEQUENCE IF NOT EXISTS booking_reference_seq START WITH 1;

-- 2. Create booking_requests table
CREATE TABLE IF NOT EXISTS booking_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_reference text UNIQUE DEFAULT NULL,
  customer_name text NOT NULL,
  phone text NOT NULL,
  email text NOT NULL,
  package_name text NOT NULL,
  package_id integer,
  travel_date date NOT NULL,
  boarding_point text NOT NULL,
  number_of_travellers integer NOT NULL,
  special_requirements text,
  
  booking_amount numeric(10,2) NOT NULL DEFAULT 0.00,
  advance_amount numeric(10,2) NOT NULL DEFAULT 5000.00,
  
  payment_method text DEFAULT 'UPI',
  transaction_id text,
  payment_screenshot text, -- URL to public storage bucket file
  
  payment_status text NOT NULL DEFAULT 'Unpaid',
  booking_status text NOT NULL DEFAULT 'Pending',
  
  assigned_staff text,
  admin_notes text,
  
  source text DEFAULT 'Direct',
  page_url text,
  utm_source text,
  utm_campaign text,
  
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 3. Trigger to auto-generate unique booking_reference: KY-BKG-2026-000001
CREATE OR REPLACE FUNCTION set_booking_reference()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.booking_reference IS NULL THEN
    NEW.booking_reference := 'KY-BKG-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('booking_reference_seq')::text, 6, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_set_booking_reference
BEFORE INSERT ON booking_requests
FOR EACH ROW
EXECUTE FUNCTION set_booking_reference();
