-- Migration Script: Create tour_departures table and configure security policies

-- 1. Create tour_departures table
CREATE TABLE IF NOT EXISTS public.tour_departures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id INTEGER REFERENCES public.packages(id) ON DELETE SET NULL,
    package_name TEXT NOT NULL,
    departure_date DATE NOT NULL,
    total_seats INTEGER NOT NULL DEFAULT 40,
    booked_seats INTEGER NOT NULL DEFAULT 0,
    available_seats INTEGER NOT NULL DEFAULT 40,
    status TEXT NOT NULL DEFAULT 'Open', -- 'Open', 'Sold Out', 'Guaranteed', 'Cancelled'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT unique_package_departure UNIQUE (package_name, departure_date)
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.tour_departures ENABLE ROW LEVEL SECURITY;

-- 3. Create Policy: Allow authenticated users (admin dashboard) full CRUD access
CREATE POLICY "Allow admin full access departures" 
ON public.tour_departures 
FOR ALL 
TO authenticated 
USING (true);

-- 4. Create Policy: Allow public read-only access (for checking availability on booking client)
CREATE POLICY "Allow public read departures" 
ON public.tour_departures 
FOR SELECT 
TO public 
USING (true);

-- 5. Create index for fast query lookups on package and date
CREATE INDEX IF NOT EXISTS idx_tour_departures_search ON public.tour_departures (package_name, departure_date);
