-- Create inquiries table
CREATE TABLE IF NOT EXISTS public.inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    package TEXT,
    travel_date TEXT,
    guests TEXT,
    message TEXT,
    status TEXT DEFAULT 'Pending', -- 'Pending', 'Contacted', 'Resolved'
    source TEXT,                  -- 'homepage', 'package_page', 'contact_page', 'booking_page', 'whatsapp'
    page_url TEXT,
    utm_source TEXT,
    utm_campaign TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (visitors filling the contact/booking forms)
CREATE POLICY "Allow public insert" 
ON public.inquiries 
FOR INSERT 
WITH CHECK (true);

-- Allow authenticated users (admin dashboard) full access
CREATE POLICY "Allow admin full access" 
ON public.inquiries 
FOR ALL 
TO authenticated 
USING (true);

-- Create index for quick duplicate checks on phone number and created_at
CREATE INDEX IF NOT EXISTS idx_inquiries_phone_created ON public.inquiries (phone, created_at DESC);

-- Create booking_cancellations table
CREATE TABLE IF NOT EXISTS public.booking_cancellations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id TEXT NOT NULL,
    customer_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT NOT NULL,
    package_name TEXT NOT NULL,
    travel_date TEXT NOT NULL,
    cancellation_reason TEXT NOT NULL,
    refund_policy_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    status TEXT DEFAULT 'Pending',           -- 'Pending', 'Under Review', 'Approved', 'Rejected', 'Completed'
    refund_status TEXT DEFAULT 'Eligible',    -- 'Not Eligible', 'Eligible', 'Refund Initiated', 'Refund Processed'
    admin_notes TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.booking_cancellations ENABLE ROW LEVEL SECURITY;

-- Allow public insert (visitors submitting cancellation requests)
CREATE POLICY "Allow public insert cancellations" 
ON public.booking_cancellations 
FOR INSERT 
WITH CHECK (true);

-- Allow authenticated users (admin dashboard) full access
CREATE POLICY "Allow admin full access cancellations" 
ON public.booking_cancellations 
FOR ALL 
TO authenticated 
USING (true);

-- Create index for quick lookups on booking_id and status
CREATE INDEX IF NOT EXISTS idx_booking_cancellations_booking_id ON public.booking_cancellations (booking_id);
CREATE INDEX IF NOT EXISTS idx_booking_cancellations_created_at ON public.booking_cancellations (created_at DESC);
