-- Migration Script: Create booking_cancellations table and setup RLS policies

-- 1. Create the booking_cancellations table
CREATE TABLE IF NOT EXISTS public.booking_cancellations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id TEXT NOT NULL,
    customer_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT NOT NULL,
    package_name TEXT NOT NULL,
    travel_date TEXT NOT NULL,
    cancellation_reason TEXT NOT NULL,
    refund_policy_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    status TEXT DEFAULT 'Pending',           -- 'Pending', 'Under Review', 'Approved', 'Rejected', 'Completed'
    refund_status TEXT DEFAULT 'Eligible',    -- 'Not Eligible', 'Eligible', 'Refund Initiated', 'Refund Processed'
    admin_notes TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.booking_cancellations ENABLE ROW LEVEL SECURITY;

-- 3. Create Policy: Allow public insert (so web visitors can submit the cancellation form)
CREATE POLICY "Allow public insert cancellations" 
ON public.booking_cancellations 
FOR INSERT 
WITH CHECK (true);

-- 4. Create Policy: Allow authenticated users (admin panel) full access
CREATE POLICY "Allow admin full access cancellations" 
ON public.booking_cancellations 
FOR ALL 
TO authenticated 
USING (true);

-- 5. Create index for quick lookups on booking_id and status
CREATE INDEX IF NOT EXISTS idx_booking_cancellations_booking_id ON public.booking_cancellations (booking_id);
CREATE INDEX IF NOT EXISTS idx_booking_cancellations_created_at ON public.booking_cancellations (created_at DESC);
