-- Migration Script: Create admin_notifications table and configure Row Level Security (RLS)

-- 1. Create notifications table
CREATE TABLE IF NOT EXISTS public.admin_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,                  -- 'new_booking', 'payment_upload', 'cancellation_request'
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    link TEXT NOT NULL,                  -- dashboard tab or deep link (e.g. 'bookings', 'cancellations')
    is_read BOOLEAN DEFAULT FALSE NOT NULL,
    reference_id TEXT,                   -- Booking Reference or Cancellation ID
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.admin_notifications ENABLE ROW LEVEL SECURITY;

-- 3. Create Policy: Allow authenticated users (admin dashboard users) full CRUD access
CREATE POLICY "Allow admin full access notifications" 
ON public.admin_notifications 
FOR ALL 
TO authenticated 
USING (true);

-- 4. Create Index: For quick retrieval of unread notifications and ordering by date
CREATE INDEX IF NOT EXISTS idx_admin_notifications_is_read ON public.admin_notifications (is_read, created_at DESC);
