-- Migration Script: Create package_fares table, update booking_requests, update tour_departures

-- 1. Create package_fares table
CREATE TABLE IF NOT EXISTS public.package_fares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id BIGINT,
    package_name TEXT NOT NULL,
    
    sl_fare NUMERIC(10,2) NOT NULL DEFAULT 0,
    ac3_extra_charge NUMERIC(10,2) NOT NULL DEFAULT 0,
    ac2_extra_charge NUMERIC(10,2) NOT NULL DEFAULT 0,
    flight_fare NUMERIC(10,2) NOT NULL DEFAULT 0,
    
    sl_services JSONB DEFAULT '{"hotel": "Standard", "meals": "Basic", "transport": "Shared Vehicle", "support": "Normal"}'::jsonb,
    ac3_services JSONB DEFAULT '{"hotel": "Deluxe", "meals": "Standard", "transport": "AC Vehicle", "support": "Priority"}'::jsonb,
    ac2_services JSONB DEFAULT '{"hotel": "Premium", "meals": "Premium", "transport": "AC Deluxe Vehicle", "support": "Priority"}'::jsonb,
    flight_services JSONB DEFAULT '{"hotel": "Luxury", "meals": "Premium", "transport": "Premium Vehicle", "support": "VIP"}'::jsonb,
    
    is_active BOOLEAN DEFAULT TRUE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS and setup policies for package_fares
ALTER TABLE public.package_fares ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read fares" 
ON public.package_fares 
FOR SELECT 
USING (true);

-- Allow authenticated users (admin dashboard) full access
CREATE POLICY "Allow admin full access fares" 
ON public.package_fares 
FOR ALL 
TO authenticated 
USING (true);

-- 2. Update booking_requests table
ALTER TABLE public.booking_requests
ADD COLUMN IF NOT EXISTS travel_class TEXT,
ADD COLUMN IF NOT EXISTS package_cost NUMERIC(10,2) DEFAULT 0,
-- advance_amount already exists in booking_requests, but let's check balance_amount
ADD COLUMN IF NOT EXISTS balance_amount NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS hotel_category TEXT,
ADD COLUMN IF NOT EXISTS meal_category TEXT,
ADD COLUMN IF NOT EXISTS transport_category TEXT;

-- 3. Update tour_departures table for inventory management per class
ALTER TABLE public.tour_departures
ADD COLUMN IF NOT EXISTS sl_total_seats INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS sl_booked_seats INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS ac3_total_seats INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS ac3_booked_seats INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS ac2_total_seats INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS ac2_booked_seats INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS flight_total_seats INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS flight_booked_seats INTEGER DEFAULT 0;

-- Optionally, if you want to initialize default seats for existing rows:
-- UPDATE public.tour_departures SET 
--     sl_total_seats = total_seats, 
--     sl_booked_seats = booked_seats
-- WHERE sl_total_seats = 0;
